import { useState, useEffect, useCallback } from "react";
import { useRouter } from 'next/router'

import Head from "next/head";

import Card from "../components/Card";

import styles from "../styles/Home.module.scss";

const Home = ({ pokemon }) => {
	const router = useRouter();
	const { query } = router.query;
	const [results, setResults] = useState([]);
	const [resultsLength, setResultsLength] = useState('');
	const [noResults, setNoResults] = useState(true);
	const numPerPage = 12;
	const totalPages = Math.ceil(resultsLength / numPerPage);
	const [pageNum, setPageNum] = useState(1);

	useEffect(() => {
		setResults([]);
		if (query) {
			pokemon.map((monster) => {
				if (monster.name.includes(query.toLowerCase())) {
					setResults(results => [...results, monster])
				}
			});
		}
		else {
			pokemon.map((monster) => {
				setResults(results => [...results, monster])
			});			
		}
	}, [query]);

	useEffect(() => {
		if (results.length > 0) {
			setNoResults(false);
			setResultsLength(results.length);
		}
		else {
			setNoResults(true);
			setResultsLength(0);
		}
	}, [results]);

    return (
        <main className={styles.homepage}>
            <Head>
                <title>{query} search results</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
			</Head>
			{noResults && query &&
				<div className="container">
					<p>No Pokémon found with &#8220;{query}&#8221; in the name.</p>
				</div>
			}
			{!noResults &&
				<div className="container">
					{query &&
						<p>{resultsLength} Pokémon found with &#8220;{query}&#8221; .</p>
					}
					<div className={styles.homepage__cards}>
						{results.slice(0, numPerPage * pageNum).map((monster, index) => {
							return (
								<Card key={index} pokemon={monster} />
							)
						})}
					</div>
					{pageNum < totalPages &&
						<button className="btn btn--white" onClick={() => setPageNum(pageNum + 1)}>Show More</button>
					}
				</div>
			}
        </main>
    );
}

Home.getInitialProps = async () => {
	const res = await fetch('https://pokeapi.co/api/v2/pokemon?limit=897');
	const json = await res.json();
	return { pokemon: json.results };
}

export default Home;