import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.scss";
import eevee from "../samples/eevee";
import pokemon from "../samples/pokemon";

export default function Home() {
    const [query, setQuery] = useState("");
    const router = useRouter();

    useEffect(() => {
        console.log("query is: ", query);
    }, [query]);

    const searchClicky = (e) => {
        e.preventDefault();
        router.push(`/search?query=${query}`);
    };

    return (
        <main className={styles.homepage}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="wrapper">
                <h1>My Pokédex!</h1>
                {/* Just a sample form, please feel free to delete or modify as needed for your implementation */}
                <form action="" onSubmit={(e) => searchClicky(e)}>
                    <input
                        type="search"
                        name="search"
                        id="search"
                        value={query}
                        onChange={(e) => setQuery(e.target.value)}
                    />
                    <button type="submit">Search!</button>
                </form>
                {/* List of favorite pokemon will start here */}
            </div>
        </main>
    );
}
