import { useState, useEffect, useCallback } from "react";
import { useRouter } from 'next/router'

import { database } from '../services/firebase';
import { auth } from '../services/firebase';
import { useAuthState } from 'react-firebase-hooks/auth';

import Head from "next/head";

import Card from "../components/Card";

import styles from "../styles/Home.module.scss";

const Home = ({ pokemon }) => {
	const router = useRouter();
	const { query } = router.query;
	const [user] = useAuthState(auth);
	const [userInfo, setUserInfo] = useState('');
	const [userId, setUserId] = useState('');
	const [results, setResults] = useState([]);
	const [resultsLength, setResultsLength] = useState('');
	const [noResults, setNoResults] = useState(true);
	const numPerPage = 12;
	const totalPages = Math.ceil(resultsLength / numPerPage);
	const [pageNum, setPageNum] = useState(1);
	const [favorites, setFavorites] = useState([]);

	useEffect(() => {
		database.ref('users').once('value', function (snapshot) {
			snapshot.forEach(user => {
				setUserInfo(user.val());
				if (user.val().favorites) {
					setFavorites(user.val().favorites);
				}
			});
		});
	}, []);

	const callback = useCallback((id) => {
		setUserId(id.user);
		console.log('id ', id.id);
		if (id.favorite) {
			setFavorites(favorites => [...favorites, id.id]);
		}
		else {
			setFavorites(favorites => favorites.filter(favorite => favorite !== id.id));
		}
	}, []);

	useEffect(() => {
		setResults([]);
		if (query) {
			pokemon.map((monster) => {
				if (monster.name.includes(query.toLowerCase())) {
					setResults(results => [...results, monster])
				}
			});
		}
		else {
			pokemon.map((monster) => {
				setResults(results => [...results, monster])
			});			
		}
	}, [query]);

	useEffect(() => {
		if (results.length > 0) {
			setNoResults(false);
			setResultsLength(results.length);
		}
		else {
			setNoResults(true);
			setResultsLength(0);
		}
	}, [results]);


	useEffect(() => {
		database.ref()
		.child('/users/' + userInfo.uid)
		.update({
			favorites: favorites
		})
		.catch()
	}, [favorites]);

    return (
        <main className={styles.homepage}>
            <Head>
                <title>{query} search results</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
			</Head>
			{noResults && query &&
				<div className="container">
					<p>No Pokémon found with &#8220;{query}&#8221; in the name.</p>
				</div>
			}
			{!noResults &&
				<div className="container">
					{query &&
						<p>{resultsLength} Pokémon found with &#8220;{query}&#8221; .</p>
					}
					<div className={styles.homepage__cards}>
						{results.slice(0, numPerPage * pageNum).map((monster, index) => {
							return (
								<Card key={index} pokemon={monster} parentCallback={callback} />
							)
						})}
					</div>
					{pageNum < totalPages &&
						<button className="btn btn--white" onClick={() => setPageNum(pageNum + 1)}>Show More</button>
					}
				</div>
			}
        </main>
    );
}

Home.getInitialProps = async () => {
	const res = await fetch('https://pokeapi.co/api/v2/pokemon?limit=897');
	const json = await res.json();
	return { pokemon: json.results };
}

export default Home;