import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.scss";
import pokemon from "../samples/pokemon";

export default function search() {
    const [query, setQuery] = useState("");

    // This will fire once when the page is loaded for the first time
    useEffect(() => {
        // Let's set the query state to match the query url parameter that's passed from the homepage
        const search = window.location.search;
        const urlParams = new URLSearchParams(search);
        const urlQuery = urlParams.get("query");
        if (urlQuery && urlQuery !== "") {
            setQuery(urlQuery);
        }
    }, []);

    // This will fire every time the 'query' state is changed
    useEffect(() => {
        console.log("query is: ", query);
    }, [query]);

    return (
        <main className={styles.homepage}>
            <Head>
                <title>{query} search results</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="wrapper">
                {/* Just a sample form, please feel free to delete or modify as needed for your implementation */}
                {!query && <h1>Type below to begin search</h1>}
                {query && <h1>Search</h1>}
                <form action="">
                    <input
                        type="search"
                        name="search"
                        id="search"
                        value={query}
                        onChange={(e) => setQuery(e.target.value)}
                    />
                    {/* <button type="submit">Search!</button> */}
                </form>
                {query && (
                    <div className="results">
                        <h2>Searching for {query}</h2>
                        <p>XXX Pokémon Found</p>
                        <div className={styles.cards}>
                            {pokemon.results.map((monster) => {
                                if (monster.name.includes(query)) {
                                    return (
                                        <Link href="/single">
                                            <a>
                                                <div className={styles.card}>
                                                    <h3>{monster.name}</h3>
                                                </div>
                                            </a>
                                        </Link>
                                    );
                                }
                            })}
                        </div>
                    </div>
                )}
            </div>
        </main>
    );
}
