import { useEffect, useState } from "react";
import { useRouter } from 'next/router'

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Card from "../components/Card";

import styles from "../styles/Home.module.scss";

import pokemon from "../samples/pokemon";

export default function search() {
	const router = useRouter();
	const [query, setQuery] = useState('');
	const [results, setResults] = useState([]);
	const [isLoading, setLoading] = useState(true);

	useEffect(() => {
		setLoading(true);
		setQuery(router.query.query);
		setResults([]);
	}, [router.query]);

	useEffect(() => {
		setLoading(false);
		setResults([]);
		pokemon.results.filter(character => character.name.toLowerCase().includes(query)).map(filterCharacter => (
			setResults(results => [...results, filterCharacter])
		));
	}, [query]);

    if (isLoading) {
        return (
            <>
            </>
        );
	}

    return (
        <main className={styles.homepage}>
            <Head>
                <title>{query} search results</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
			<div className="container">
				{results.length > 0 && 
					<p>{results.length} Pokémon found with &#8220;{query}&#8221; in the name.</p>
				}
				<div className={styles.homepage__cards}>
					{results &&
						results.map((character, index) => {
							return (
								<Card key={index} pokemon={character} />
							)
						})
					}
					{results.length < 1 &&
						<p>Sorry, no Pokémon found with &#8220;{query}&#8221; in the name.</p>
					}
				</div>
            </div>
        </main>
    );
}
